### PR TITLE
REST API Implementation

### PR DESCRIPTION
**Pull request by cseufert**
- Added unit tests to capture, limit & ping api methods.
- Removed unused REST API Functions
- Refactored REST API Functions to contain less duplicate code (createRespone, sendData, etc)
- Updated REST API to be compatible with openpay 3.x
- Added example to readme

### CODE REVIEW

**Comment by cseufert** [comment]
@sudiptpa This is all working now, this code will be live in production in the next few hours, so I am looking forward to it being merged, and an updated release that I can use, rather than that using this via a git link in composer.

**Comment by sudiptpa** [comment]
@cseufert could you please stay on the git link in composer for few days, i've some clients using this package in the XML API, and the Openpay officials requested to integrate REST API, as the REST API is security and overal improvement over their XML API, i've some game plan now to complete it and tested, i will try and finish my plan this coming weekend.

I'll let you know once i progress and release the changes, i will also follow up on your changes and see how i can catch up with it, so we both can benefit from it, and release the next stable release of this package.

Many thanks for the interest and working on the update of this package, appreciate your work on it.

**Comment by cseufert** [comment]
@sudiptpa it is no problem to stay on this git release for the time being. If there are any desicisions that have been made during the implementation you would like changed, or gone about differently, I am more than happy to work with you. 

Here a list of things that vary from the XML implementation:
- API keys are now called `apiKey` for username and `apiToken` for password
- To start the application flow you use the `authorize()` method, rather than order & purchase
- To complete order you use the `capture()` method.
- Person details are all handled via the Omnipay `Card` object, this is contact details + ship + (optional) billing address.
- Items use `RestItemInterface` with a `RestItem` implemntation, which uses `price` & `totalPrice` rather than `itemRetailUnitPrice` and `itemRetailCharge`.
- Tests include mock responses from API only, tests do not include comparing request body.
- `refund()` is the only method that has no test with mock response

**Comment by sudiptpa** [comment]
@cseufert thanks for clarification, i've previously gone through their API docs, i will follow up your listed points while i work on it.

**Comment by sudiptpa** [comment]
@cseufert i made some progress last weekend, and are you able to review - [#6](https://github.com/sudiptpa/openpay/pull/6), and test the features.

I cannot merge you PR because you have branched off of master and which is 3.* version of Omnipay, and i need to release this feature for both 2.0, 3.0 support.

I'll full review you PR and take the code as many as i can from there and add tests as well before i merge it. So give your feedback if you see any issues and bugs.

I hope to release a new tag in the coming weekend if it goes as planned.

**Comment by sudiptpa** [comment]
https://github.com/sudiptpa/openpay/pull/6 got merged. So closing this PR, feel free to submit a PR if anything goes wrong with it.

**Pull request closed without merging**
